# Use a imagem base do Node.js
FROM node:16

# Crie o diretório de trabalho
WORKDIR /app

# Copie o package.json e o package-lock.json (se houver) para o contêiner
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos do projeto para dentro do contêiner
COPY . .

# Exponha a porta
EXPOSE 3000

# Comando para iniciar o servidor ou rodar testes
CMD ["npm", "start"]
