# Use a imagem base do Node.js
FROM node:16

# Crie o diretório de trabalho
WORKDIR /app

# Copie os arquivos do seu projeto para o diretório de trabalho
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos
COPY . .

# Exponha a porta
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "start"]
