# Usando uma versão mais recente do Node para compatibilidade
FROM node:16-alpine

# Diretório de trabalho
WORKDIR /app

# Copiando arquivos package.json e package-lock.json
COPY package*.json ./

# Instalando dependências, suprimindo avisos para manter o log mais limpo
RUN npm install --legacy-peer-deps

# Copiando o restante dos arquivos para o container
COPY . .

# Expondo a porta que a aplicação usará
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
