# frontend/Dockerfile
FROM node:14-alpine

WORKDIR /app

# Instalar dependências e compilar o código
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Expor a porta 3000 para o servidor React
EXPOSE 3000
CMD ["npm", "start"]
